# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            viewer: true
            entities:
                    App\Entity\Character:
                        enabled: true
                    App\Entity\User:
                        enabled: true
                    App\Entity\Scenario:
                        enabled: true
                    App\Entity\Building:
                        enabled: true
                    App\Entity\Token:
                        enabled: true
            
